// src/lib/components/apps/Blue-Code-App/FileTreeView.svelte
<script lang="ts">
  import { Folder, ChevronRight, ChevronDown, FileCode, Trash2, Edit2 } from 'lucide-svelte';
  import type { FileNode } from './types';
  import { createEventDispatcher } from 'svelte';

  export let nodes: FileNode[];
  export let level = 0;
  export let selectedDir: string;

  const dispatch = createEventDispatcher<{ openFile: string; toggleDir: FileNode; rename: FileNode; delete: FileNode }>();
</script>

{#each nodes as node (node.path)}
  <div>
    <div
      class="flex items-center gap-1 py-0.5 px-1 rounded cursor-pointer hover:bg-white/5 group text-sm {node.type === 'directory' && node.path === selectedDir ? 'bg-blue-600/10' : ''}"
      style="padding-left:{level * 12 + 4}px;"
      on:dblclick={() => node.type === 'file' && dispatch('openFile', node.path)}
      on:click={() => node.type === 'directory' && dispatch('toggleDir', node)}>
      {#if node.type === 'directory'}
        <span class="text-slate-500 w-4 shrink-0">{#if node.expanded}<ChevronDown size={12} />{:else}<ChevronRight size={12} />{/if}</span>
      {/if}
      {#if node.type === 'directory'}<Folder size={14} class="text-blue-400 shrink-0" />{:else}<FileCode size={14} class="text-yellow-400 shrink-0" />{/if}
      <span class="truncate flex-1">{node.name}</span>
      <div class="flex gap-0.5 opacity-0 group-hover:opacity-100 ml-auto shrink-0">
        {#if node.type === 'file'}
          <button on:click|stopPropagation={() => dispatch('openFile', node.path)} class="p-0.5 hover:bg-white/10 rounded text-slate-500" title="Open"><FileCode size={11} /></button>
        {/if}
        <button on:click|stopPropagation={() => dispatch('rename', node)} class="p-0.5 hover:bg-white/10 rounded text-slate-500 hover:text-blue-400" title="Rename"><Edit2 size={11} /></button>
        <button on:click|stopPropagation={() => dispatch('delete', node)} class="p-0.5 hover:bg-white/10 rounded text-slate-500 hover:text-red-400" title="Delete"><Trash2 size={11} /></button>
      </div>
    </div>
    {#if node.type === 'directory' && node.expanded && node.children}
      <svelte:self nodes={node.children} level={level + 1} {selectedDir}
        on:openFile on:toggleDir on:rename on:delete />
    {/if}
  </div>
{/each}

// src/components/apps/Blue-Code-App/src/FileTreeView.tsx
import React from 'react';
import { Folder, ChevronRight, ChevronDown, FileCode, Trash2, Edit2 } from 'lucide-react';
import { FileNode } from './types';

interface Props {
    nodes: FileNode[];
    level?: number;
    onOpenFile: (path: string) => void;
    onToggleDir: (node: FileNode) => void;
    onRename: (node: FileNode) => void;
    onDelete: (node: FileNode) => void;
    selectedDir: string;
}

const FileTreeView: React.FC<Props> = ({ nodes, level = 0, onOpenFile, onToggleDir, onRename, onDelete, selectedDir }) => (
    <>
        {nodes.map(node => (
            <div key={node.path}>
                <div
                    className={`flex items-center gap-1 py-0.5 px-1 rounded cursor-pointer hover:bg-white/5 group text-sm ${
                        node.type === 'directory' && node.path === selectedDir ? 'bg-blue-600/10' : ''
                    }`}
                    style={{ paddingLeft: `${level * 12 + 4}px` }}
                    onDoubleClick={() => node.type === 'file' && onOpenFile(node.path)}
                    onClick={() => node.type === 'directory' && onToggleDir(node)}
                >
                    {node.type === 'directory' && (
                        <span className="text-slate-500 w-4 shrink-0">
                            {node.expanded ? <ChevronDown size={12} /> : <ChevronRight size={12} />}
                        </span>
                    )}
                    {node.type === 'directory'
                        ? <Folder size={14} className="text-blue-400 shrink-0" />
                        : <FileCode size={14} className="text-yellow-400 shrink-0" />}
                    <span className="truncate flex-1">{node.name}</span>
                    <div className="flex gap-0.5 opacity-0 group-hover:opacity-100 ml-auto shrink-0">
                        {node.type === 'file' && (
                            <button onClick={e => { e.stopPropagation(); onOpenFile(node.path); }}
                                className="p-0.5 hover:bg-white/10 rounded text-slate-500" title="Open">
                                <FileCode size={11} />
                            </button>
                        )}
                        <button onClick={e => { e.stopPropagation(); onRename(node); }}
                            className="p-0.5 hover:bg-white/10 rounded text-slate-500 hover:text-blue-400" title="Rename">
                            <Edit2 size={11} />
                        </button>
                        <button onClick={e => { e.stopPropagation(); onDelete(node); }}
                            className="p-0.5 hover:bg-white/10 rounded text-slate-500 hover:text-red-400" title="Delete">
                            <Trash2 size={11} />
                        </button>
                    </div>
                </div>
                {node.type === 'directory' && node.expanded && node.children && (
                    <FileTreeView
                        nodes={node.children} level={level + 1}
                        onOpenFile={onOpenFile} onToggleDir={onToggleDir}
                        onRename={onRename} onDelete={onDelete} selectedDir={selectedDir}
                    />
                )}
            </div>
        ))}
    </>
);

export default FileTreeView;
