// src/lib/components/apps/NotepadApp/NotepadApp.svelte
<script lang="ts">
  import { onMount, onDestroy, tick } from 'svelte';
  import { SystemBridge } from '../../../utils/systemBridge';
  import {
    Save, FolderOpen, Plus, X, FileText, Download,
    Bold, Italic, Hash, Search, SpellCheck,
  } from 'lucide-svelte';
  import SaveAsDialog from './SaveAsDialog.svelte';
  import { autocorrectAt } from '../../../utils/autocorrect';

  /** Set when launched from Explorer with "open this file" — see
   * ExplorerApp.svelte's handleOpen and windowManager.ts's launchArgs. */
  export let openPath: string | undefined = undefined;

  interface NoteTab { id: string; title: string; content: string; path?: string; modified: boolean; }
  interface FindState { query: string; replace: string; show: boolean; matchCase: boolean; count: number; }

  let tabs: NoteTab[] = [];
  let activeId: string | null = null;
  let find: FindState = { query: '', replace: '', show: false, matchCase: false, count: 0 };
  let wordCount = 0;
  let lineCount = 0;
  let cursorPos = { line: 1, col: 1 };
  let saveAsTarget: NoteTab | null = null;
  let textareaEl: HTMLTextAreaElement;
  let autosaveTimer: ReturnType<typeof setInterval>;
  let findInputEl: HTMLInputElement;
  let autocorrectEnabled = true;

  $: activeTab = tabs.find((t) => t.id === activeId) ?? null;

  onMount(() => {
    const id = `note-${Date.now()}`;
    tabs = [{ id, title: 'Untitled', content: '', modified: false }];
    activeId = id;

    SystemBridge.executeCommand('cat ~/.cache/Blue-Environment/notepad-autosave.json 2>/dev/null').then((r) => {
      const out = typeof r === 'string' ? r : (r as any)?.stdout || '';
      try {
        const saved = JSON.parse(out);
        if (saved.content) {
          tabs = tabs.map((t) => (t.id === activeId ? { ...t, content: saved.content, title: saved.title || 'Untitled', modified: false } : t));
        }
      } catch {}
    });

    autosaveTimer = setInterval(() => {
      tabs.forEach((tab) => {
        if (tab.modified && !tab.path) saveToCacheNote(tab);
        else if (tab.modified && tab.path) writeToPath(tab);
      });
    }, 30000);

    if (openPath) openFileByPath(openPath);
  });
  onDestroy(() => clearInterval(autosaveTimer));

  async function saveToCacheNote(tab: NoteTab) {
    const data = JSON.stringify({ content: tab.content, title: tab.title });
    await SystemBridge.executeCommand(`mkdir -p ~/.cache/Blue-Environment && printf '%s' ${JSON.stringify(data)} > ~/.cache/Blue-Environment/notepad-autosave.json`).catch(() => {});
  }

  async function writeToPath(tab: NoteTab) {
    if (!tab.path) return false;
    try {
      const expandedPath = tab.path.startsWith('~/') ? tab.path.replace('~', '$HOME') : tab.path;
      await SystemBridge.executeCommand(`mkdir -p "$(dirname "${expandedPath}")" && printf '%s' ${JSON.stringify(tab.content)} > "${expandedPath}"`);
      return true;
    } catch { return false; }
  }

  function updateContent(id: string, content: string) {
    tabs = tabs.map((t) => (t.id === id ? { ...t, content, modified: true } : t));
    const lines = content.split('\n');
    lineCount = lines.length;
    wordCount = content.trim() ? content.trim().split(/\s+/).length : 0;
  }

  /**
   * Textarea `input` handler — replaces the old inline
   * `updateContent(activeTab.id, e.currentTarget.value)` arrow so
   * autocorrect (see `utils/autocorrect.ts`) can run in the same
   * synchronous handler, on the DOM element's live value/cursor,
   * before Svelte's own reactivity re-renders anything. Doing the
   * correction here (rather than via a second, independently-attached
   * `input` listener) avoids a real ordering hazard: a second listener
   * reading `activeTab.content` could see a stale value, since Svelte
   * reactive statements don't recompute synchronously mid-event.
   */
  function handleInput(e: Event) {
    if (!activeTab) return;
    const ta = e.currentTarget as HTMLTextAreaElement;
    let content = ta.value;
    let cursor = ta.selectionStart;
    if (autocorrectEnabled) {
      const result = autocorrectAt(content, cursor);
      if (result) {
        content = result.newText;
        cursor = result.newCursor;
        // The textarea's own DOM value already reflects the keystroke;
        // writing the corrected text back into it directly (rather
        // than waiting for Svelte's `value={activeTab.content}` to
        // re-render on the next tick) keeps what's on screen and the
        // cursor position in sync with `content` immediately — a
        // visible one-frame lag here would look like the correction
        // "flickering in" late.
        ta.value = content;
        ta.setSelectionRange(cursor, cursor);
      }
    }
    updateContent(activeTab.id, content);
  }

  function newTab() {
    const id = `note-${Date.now()}`;
    tabs = [...tabs, { id, title: 'Untitled', content: '', modified: false }];
    activeId = id;
  }

  function closeTab(id: string, e: MouseEvent) {
    e.stopPropagation();
    const next = tabs.filter((t) => t.id !== id);
    if (next.length === 0) {
      const newId = `note-${Date.now()}`;
      activeId = newId;
      tabs = [{ id: newId, title: 'Untitled', content: '', modified: false }];
      return;
    }
    if (activeId === id) activeId = next[next.length - 1].id;
    tabs = next;
  }

  async function openFileByPath(path: string) {
    try {
      const text = await SystemBridge.readFile(path);
      const name = path.split('/').pop() || path;
      const id = `note-${Date.now()}`;
      // If mount created a lone empty "Untitled" tab and this is the
      // first real file being opened, replace it instead of leaving a
      // stray blank tab sitting there.
      const onlyEmptyUntitled = tabs.length === 1 && !tabs[0].modified && !tabs[0].path && tabs[0].content === '';
      const newTab = { id, title: name, content: text || '', path, modified: false };
      tabs = onlyEmptyUntitled ? [newTab] : [...tabs, newTab];
      activeId = id;
    } catch (e) { console.error('Failed to open file:', e); }
  }

  async function openFile() {
    const path = await SystemBridge.pickFile(
      [
        { name: 'Text Files', extensions: ['txt', 'md', 'json', 'csv', 'log', 'toml', 'yaml', 'yml', 'sh', 'py', 'js', 'ts', 'css', 'html', 'xml', 'ini', 'conf'] },
        { name: 'All Files', extensions: ['*'] },
      ],
      'Open File'
    );
    if (!path) return;
    await openFileByPath(path);
  }

  async function saveFile(tab?: NoteTab) {
    const target = tab ?? activeTab;
    if (!target) return;
    if (target.path) {
      const ok = await writeToPath(target);
      if (ok) tabs = tabs.map((t) => (t.id === target.id ? { ...t, modified: false } : t));
    } else {
      saveAsTarget = target;
    }
  }

  function saveAs(tab?: NoteTab) {
    const target = tab ?? activeTab;
    if (!target) return;
    saveAsTarget = target;
  }

  async function handleSaveAsConfirm(e: CustomEvent<{ path: string; format: string }>) {
    const target = saveAsTarget;
    if (!target) return;
    saveAsTarget = null;

    const fileName = e.detail.path.split('/').pop() || 'Untitled';
    const updatedTab: NoteTab = { ...target, path: e.detail.path, title: fileName, modified: false };
    const ok = await writeToPath(updatedTab);

    if (ok) {
      tabs = tabs.map((t) => (t.id === updatedTab.id ? updatedTab : t));
    } else {
      const blob = new Blob([target.content], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url; a.download = fileName; a.click();
      URL.revokeObjectURL(url);
      tabs = tabs.map((t) => (t.id === target.id ? { ...t, modified: false } : t));
    }
  }

  function doFind() {
    if (!activeTab || !find.query) { find = { ...find, count: 0 }; return; }
    const flags = find.matchCase ? 'g' : 'gi';
    const matches = [...activeTab.content.matchAll(new RegExp(find.query.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), flags))];
    find = { ...find, count: matches.length };
    if (matches.length > 0 && textareaEl) {
      textareaEl.focus();
      textareaEl.setSelectionRange(matches[0].index!, matches[0].index! + find.query.length);
    }
  }

  function doReplace() {
    if (!activeTab || !find.query) return;
    const flags = find.matchCase ? 'g' : 'gi';
    const newContent = activeTab.content.replace(new RegExp(find.query.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), flags), find.replace);
    updateContent(activeTab.id, newContent);
  }

  function handleCursorMove(e: Event) {
    const t = e.target as HTMLTextAreaElement;
    const before = t.value.substring(0, t.selectionStart ?? 0);
    const lines = before.split('\n');
    cursorPos = { line: lines.length, col: lines[lines.length - 1].length + 1 };
  }

  function insertText(before: string, after = '') {
    const ta = textareaEl;
    if (!ta || !activeTab) return;
    const start = ta.selectionStart, end = ta.selectionEnd;
    const sel = activeTab.content.substring(start, end);
    const newContent = activeTab.content.substring(0, start) + before + sel + after + activeTab.content.substring(end);
    updateContent(activeTab.id, newContent);
    setTimeout(() => { ta.selectionStart = start + before.length; ta.selectionEnd = start + before.length + sel.length; ta.focus(); }, 0);
  }

  function handleKeyDown(e: KeyboardEvent) {
    if (e.key === 'Tab') { e.preventDefault(); insertText('    '); }
    if (e.ctrlKey && e.key === 's' && !e.shiftKey) { e.preventDefault(); saveFile(); }
    if (e.ctrlKey && e.key === 's' && e.shiftKey) { e.preventDefault(); saveAs(); }
    if (e.ctrlKey && e.key === 'f') { e.preventDefault(); find = { ...find, show: !find.show }; }
  }

  $: if (find.show) tick().then(() => findInputEl?.focus());
</script>

<div class="flex flex-col h-full bg-slate-900 text-white overflow-hidden">
  {#if saveAsTarget}
    <SaveAsDialog defaultName={saveAsTarget.title} on:confirm={handleSaveAsConfirm} on:cancel={() => (saveAsTarget = null)} />
  {/if}

  <div class="shrink-0 flex items-center gap-1 px-3 py-2 bg-slate-800 border-b border-white/5">
    <button on:click={newTab} class="p-1.5 hover:bg-white/10 rounded-lg text-slate-400 hover:text-white" title="New Tab (Ctrl+T)"><Plus size={15} /></button>
    <button on:click={openFile} class="p-1.5 hover:bg-white/10 rounded-lg text-slate-400 hover:text-white" title="Open file"><FolderOpen size={15} /></button>
    <button on:click={() => saveFile()} class="p-1.5 hover:bg-white/10 rounded-lg text-slate-400 hover:text-white" title="Save (Ctrl+S)"><Save size={15} /></button>
    <button on:click={() => saveAs()} class="p-1.5 hover:bg-white/10 rounded-lg text-slate-400 hover:text-white" title="Save As (Ctrl+Shift+S)"><Download size={15} /></button>
    <div class="w-px h-5 bg-white/10 mx-1" />
    <button on:click={() => insertText('**', '**')} class="p-1.5 hover:bg-white/10 rounded-lg text-slate-400 hover:text-white" title="Bold"><Bold size={15} /></button>
    <button on:click={() => insertText('*', '*')} class="p-1.5 hover:bg-white/10 rounded-lg text-slate-400 hover:text-white" title="Italic"><Italic size={15} /></button>
    <button on:click={() => insertText('# ')} class="p-1.5 hover:bg-white/10 rounded-lg text-slate-400 hover:text-white" title="Heading"><Hash size={15} /></button>
    <div class="w-px h-5 bg-white/10 mx-1" />
    <button on:click={() => (find = { ...find, show: !find.show })} class="p-1.5 rounded-lg {find.show ? 'bg-blue-500/20 text-blue-400' : 'hover:bg-white/10 text-slate-400'}" title="Find (Ctrl+F)">
      <Search size={15} />
    </button>
    <button on:click={() => (autocorrectEnabled = !autocorrectEnabled)}
      class="p-1.5 rounded-lg text-xs font-medium {autocorrectEnabled ? 'bg-blue-500/20 text-blue-400' : 'hover:bg-white/10 text-slate-500'}"
      title={autocorrectEnabled ? 'Autocorrect: on — fixes common typos as you type' : 'Autocorrect: off'}>
      <SpellCheck size={15} />
    </button>
    {#if activeTab?.path}
      <div class="ml-auto text-xs text-slate-600 truncate max-w-[200px] font-mono" title={activeTab.path}>{activeTab.path}</div>
    {/if}
  </div>

  <div class="shrink-0 flex bg-slate-800/50 border-b border-white/5 overflow-x-auto scrollbar-hide">
    {#each tabs as tab (tab.id)}
      <div on:click={() => (activeId = tab.id)} role="button" tabindex="0" on:keydown={(e) => { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); (() => (activeId = tab.id))(); } }}
        class="flex items-center gap-1.5 px-4 py-2 cursor-pointer shrink-0 border-r border-white/5 text-sm group max-w-[150px] {activeId === tab.id ? 'bg-slate-900 text-white' : 'text-slate-400 hover:text-white hover:bg-slate-700/50'}">
        <FileText size={13} class="shrink-0" />
        <span class="truncate">{tab.title}</span>
        {#if tab.modified}<span class="w-1.5 h-1.5 rounded-full bg-blue-400 shrink-0" />{/if}
        <button on:click={(e) => closeTab(tab.id, e)} class="opacity-0 group-hover:opacity-100 hover:text-red-400 ml-0.5 shrink-0"><X size={11} /></button>
      </div>
    {/each}
    <button on:click={newTab} class="p-2.5 hover:bg-slate-700/50 text-slate-500 hover:text-white shrink-0"><Plus size={13} /></button>
  </div>

  {#if find.show}
    <div class="shrink-0 flex items-center gap-2 px-3 py-2 bg-slate-800/80 border-b border-white/5">
      <div class="relative">
        <Search size={13} class="absolute left-2 top-1/2 -translate-y-1/2 text-slate-500" />
        <input bind:this={findInputEl} bind:value={find.query} on:keydown={(e) => e.key === 'Enter' && doFind()} placeholder="Find..."
          class="bg-slate-900 border border-white/10 rounded-lg pl-7 pr-3 py-1.5 text-sm text-white w-44 focus:outline-none focus:border-blue-500/50" />
      </div>
      <input bind:value={find.replace} placeholder="Replace with..." class="bg-slate-900 border border-white/10 rounded-lg px-3 py-1.5 text-sm text-white w-40 focus:outline-none" />
      <button on:click={doFind} class="px-2.5 py-1.5 bg-slate-700 hover:bg-slate-600 rounded-lg text-xs transition-colors">Find</button>
      <button on:click={doReplace} class="px-2.5 py-1.5 bg-blue-600 hover:bg-blue-500 rounded-lg text-xs transition-colors">Replace All</button>
      <label class="flex items-center gap-1 text-xs text-slate-400 cursor-pointer">
        <input type="checkbox" bind:checked={find.matchCase} class="accent-blue-500" /> Aa
      </label>
      {#if find.count > 0}<span class="text-xs text-slate-500">{find.count} matches</span>{/if}
      <button on:click={() => (find = { ...find, show: false })} class="ml-auto text-slate-500 hover:text-white"><X size={14} /></button>
    </div>
  {/if}

  <div class="flex-1 overflow-hidden">
    {#if activeTab}
      <textarea
        bind:this={textareaEl}
        value={activeTab.content}
        on:input={handleInput}
        on:keydown={handleKeyDown}
        on:keyup={handleCursorMove}
        on:click={handleCursorMove}
        spellcheck="false"
        class="w-full h-full bg-slate-950 text-slate-100 font-mono text-sm p-4 resize-none focus:outline-none leading-relaxed"
        placeholder="Start typing…  •  Ctrl+S to save  •  Ctrl+Shift+S for Save As"
        style="font-family:'JetBrains Mono','Fira Code',monospace; tab-size:4;"
      />
    {/if}
  </div>

  <div class="shrink-0 flex items-center justify-between px-4 py-1 bg-slate-800 border-t border-white/5 text-xs text-slate-500">
    <div class="flex gap-4">
      <span>Ln {cursorPos.line}, Col {cursorPos.col}</span>
      <span>{lineCount} lines</span>
      <span>{wordCount} words</span>
      {#if activeTab?.content.length}<span>{activeTab.content.length} chars</span>{/if}
    </div>
    <div class="flex gap-3">
      {#if activeTab?.modified}
        <span class="text-yellow-500 cursor-pointer hover:text-yellow-300" on:click={() => saveFile()} title="Click to save">● Unsaved</span>
      {/if}
      {#if activeTab?.path}
        <span class="text-green-600" title={activeTab.path}>Saved</span>
      {:else}
        <span class="text-slate-600">Not saved to disk</span>
      {/if}
      <span>UTF-8</span>
    </div>
  </div>
</div>

// src/components/apps/NotepadApp.tsx
import React, { useState, useEffect, useRef, useCallback } from 'react';
import { AppProps } from '../../types';
import { SystemBridge } from '../../utils/systemBridge';
import {
    Save, FolderOpen, Plus, X, FileText, RefreshCw,
    Bold, Italic, AlignLeft, AlignCenter, AlignRight,
    Search, Replace, Hash, ChevronDown
} from 'lucide-react';

interface NoteTab {
    id: string;
    title: string;
    content: string;
    path?: string;
    modified: boolean;
}

interface FindState {
    query: string;
    replace: string;
    show: boolean;
    matchCase: boolean;
    count: number;
}

const NotepadApp: React.FC<AppProps> = () => {
    const [tabs, setTabs] = useState<NoteTab[]>([]);
    const [activeId, setActiveId] = useState<string | null>(null);
    const [find, setFind] = useState<FindState>({ query: '', replace: '', show: false, matchCase: false, count: 0 });
    const [wordCount, setWordCount] = useState(0);
    const [lineCount, setLineCount] = useState(0);
    const [cursorPos, setCursorPos] = useState({ line: 1, col: 1 });
    const textareaRef = useRef<HTMLTextAreaElement>(null);
    const autosaveRef = useRef<ReturnType<typeof setInterval>>();

    const activeTab = tabs.find(t => t.id === activeId) ?? null;

    // Create initial tab
    useEffect(() => {
        const id = `note-${Date.now()}`;
        setTabs([{ id, title: 'Untitled', content: '', modified: false }]);
        setActiveId(id);
    }, []);

    // Autosave every 30s
    useEffect(() => {
        autosaveRef.current = setInterval(() => {
            tabs.forEach(tab => {
                if (tab.modified) saveToCacheNote(tab);
            });
        }, 30000);
        return () => clearInterval(autosaveRef.current);
    }, [tabs]);

    // Load from cache on first tab creation
    useEffect(() => {
        if (tabs.length === 1 && activeId) {
            SystemBridge.executeCommand(`cat ~/.cache/Blue-Environment/notepad-autosave.json 2>/dev/null`)
                .then(r => {
                    const out = typeof r === 'string' ? r : r?.stdout || '';
                    try {
                        const saved = JSON.parse(out);
                        if (saved.content) {
                            setTabs(prev => prev.map(t => t.id === activeId ? {
                                ...t, content: saved.content, title: saved.title || 'Untitled', modified: false
                            } : t));
                        }
                    } catch {}
                });
        }
    }, []);

    const saveToCacheNote = async (tab: NoteTab) => {
        const data = JSON.stringify({ content: tab.content, title: tab.title });
        await SystemBridge.executeCommand(`mkdir -p ~/.cache/Blue-Environment && cat > ~/.cache/Blue-Environment/notepad-autosave.json << 'JSON'\n${data}\nJSON`).catch(() => {});
    };

    const updateContent = (id: string, content: string) => {
        setTabs(prev => prev.map(t => t.id === id ? { ...t, content, modified: true } : t));
        const lines = content.split('\n');
        setLineCount(lines.length);
        setWordCount(content.trim() ? content.trim().split(/\s+/).length : 0);
    };

    const newTab = () => {
        const id = `note-${Date.now()}`;
        setTabs(prev => [...prev, { id, title: 'Untitled', content: '', modified: false }]);
        setActiveId(id);
    };

    const closeTab = (id: string, e: React.MouseEvent) => {
        e.stopPropagation();
        setTabs(prev => {
            const next = prev.filter(t => t.id !== id);
            if (next.length === 0) {
                const newId = `note-${Date.now()}`;
                setActiveId(newId);
                return [{ id: newId, title: 'Untitled', content: '', modified: false }];
            }
            if (activeId === id) setActiveId(next[next.length - 1].id);
            return next;
        });
    };

    const openFile = async () => {
        const path = await SystemBridge.pickFile([
            { name: 'Text Files', extensions: ['txt','md','json','csv','log','toml','yaml','yml','sh','py','js','ts','css','html','xml','ini','conf'] },
            { name: 'All Files', extensions: ['*'] },
        ], 'Open File');
        if (!path) return;
        try {
            const text = await SystemBridge.readFile(path);
            const name = path.split('/').pop() || path;
            const id = `note-${Date.now()}`;
            setTabs(prev => [...prev, { id, title: name, content: text || '', path, modified: false }]);
            setActiveId(id);
        } catch (e: any) {
            console.error('Failed to open file:', e);
        }
    };

    const saveFile = async () => {
        if (!activeTab) return;
        const blob = new Blob([activeTab.content], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url; a.download = activeTab.title.endsWith('.txt') ? activeTab.title : `${activeTab.title}.txt`;
        a.click(); URL.revokeObjectURL(url);
        setTabs(prev => prev.map(t => t.id === activeTab.id ? { ...t, modified: false } : t));
    };

    const doFind = useCallback(() => {
        if (!activeTab || !find.query) { setFind(f => ({ ...f, count: 0 })); return; }
        const flags = find.matchCase ? 'g' : 'gi';
        const matches = [...activeTab.content.matchAll(new RegExp(find.query.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), flags))];
        setFind(f => ({ ...f, count: matches.length }));
        // Scroll to first match
        if (matches.length > 0 && textareaRef.current) {
            textareaRef.current.focus();
            textareaRef.current.setSelectionRange(matches[0].index!, matches[0].index! + find.query.length);
        }
    }, [activeTab, find.query, find.matchCase]);

    const doReplace = () => {
        if (!activeTab || !find.query) return;
        const flags = find.matchCase ? 'g' : 'gi';
        const newContent = activeTab.content.replace(
            new RegExp(find.query.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), flags),
            find.replace
        );
        updateContent(activeTab.id, newContent);
    };

    const handleCursorMove = (e: React.SyntheticEvent<HTMLTextAreaElement>) => {
        const t = e.target as HTMLTextAreaElement;
        const before = t.value.substring(0, t.selectionStart);
        const lines = before.split('\n');
        setCursorPos({ line: lines.length, col: lines[lines.length - 1].length + 1 });
    };

    const insertText = (before: string, after: string = '') => {
        const ta = textareaRef.current;
        if (!ta || !activeTab) return;
        const start = ta.selectionStart, end = ta.selectionEnd;
        const sel = activeTab.content.substring(start, end);
        const newContent = activeTab.content.substring(0, start) + before + sel + after + activeTab.content.substring(end);
        updateContent(activeTab.id, newContent);
        setTimeout(() => { ta.selectionStart = start + before.length; ta.selectionEnd = start + before.length + sel.length; ta.focus(); }, 0);
    };

    const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
        // Tab key inserts spaces instead of changing focus
        if (e.key === 'Tab') {
            e.preventDefault();
            insertText('    ');
        }
        // Ctrl+S
        if (e.ctrlKey && e.key === 's') { e.preventDefault(); saveFile(); }
        // Ctrl+F
        if (e.ctrlKey && e.key === 'f') { e.preventDefault(); setFind(f => ({ ...f, show: !f.show })); }
    };

    return (
        <div className="flex flex-col h-full bg-slate-900 text-white overflow-hidden">

            {/* Toolbar */}
            <div className="shrink-0 flex items-center gap-1 px-3 py-2 bg-slate-800 border-b border-white/5">
                <button onClick={newTab} className="p-1.5 hover:bg-white/10 rounded-lg text-slate-400 hover:text-white" title="New (Ctrl+T)"><Plus size={15} /></button>
                <button onClick={openFile} className="p-1.5 hover:bg-white/10 rounded-lg text-slate-400 hover:text-white" title="Open file"><FolderOpen size={15} /></button>
                <button onClick={saveFile} className="p-1.5 hover:bg-white/10 rounded-lg text-slate-400 hover:text-white" title="Save (Ctrl+S)"><Save size={15} /></button>
                <div className="w-px h-5 bg-white/10 mx-1" />
                <button onClick={() => insertText('**', '**')} className="p-1.5 hover:bg-white/10 rounded-lg text-slate-400 hover:text-white" title="Bold"><Bold size={15} /></button>
                <button onClick={() => insertText('*', '*')} className="p-1.5 hover:bg-white/10 rounded-lg text-slate-400 hover:text-white" title="Italic"><Italic size={15} /></button>
                <button onClick={() => insertText('# ')} className="p-1.5 hover:bg-white/10 rounded-lg text-slate-400 hover:text-white" title="Heading"><Hash size={15} /></button>
                <div className="w-px h-5 bg-white/10 mx-1" />
                <button onClick={() => setFind(f => ({ ...f, show: !f.show }))} className={`p-1.5 rounded-lg ${find.show ? 'bg-blue-500/20 text-blue-400' : 'hover:bg-white/10 text-slate-400'}`} title="Find (Ctrl+F)"><Search size={15} /></button>
            </div>

            {/* Tabs */}
            <div className="shrink-0 flex bg-slate-800/50 border-b border-white/5 overflow-x-auto scrollbar-hide">
                {tabs.map(tab => (
                    <div key={tab.id} onClick={() => setActiveId(tab.id)}
                        className={`flex items-center gap-1.5 px-4 py-2 cursor-pointer shrink-0 border-r border-white/5 text-sm group max-w-[150px] ${activeId === tab.id ? 'bg-slate-900 text-white' : 'text-slate-400 hover:text-white hover:bg-slate-700/50'}`}>
                        <FileText size={13} className="shrink-0" />
                        <span className="truncate">{tab.title}</span>
                        {tab.modified && <span className="w-1.5 h-1.5 rounded-full bg-blue-400 shrink-0" />}
                        <button onClick={e => closeTab(tab.id, e)} className="opacity-0 group-hover:opacity-100 hover:text-red-400 ml-0.5 shrink-0"><X size={11} /></button>
                    </div>
                ))}
                <button onClick={newTab} className="p-2.5 hover:bg-slate-700/50 text-slate-500 hover:text-white shrink-0"><Plus size={13} /></button>
            </div>

            {/* Find bar */}
            {find.show && (
                <div className="shrink-0 flex items-center gap-2 px-3 py-2 bg-slate-800/80 border-b border-white/5">
                    <div className="relative">
                        <Search size={13} className="absolute left-2 top-1/2 -translate-y-1/2 text-slate-500" />
                        <input value={find.query} onChange={e => setFind(f => ({ ...f, query: e.target.value }))}
                            onKeyDown={e => e.key === 'Enter' && doFind()} placeholder="Find..."
                            className="bg-slate-900 border border-white/10 rounded-lg pl-7 pr-3 py-1.5 text-sm text-white w-44 focus:outline-none focus:border-blue-500/50" autoFocus />
                    </div>
                    <input value={find.replace} onChange={e => setFind(f => ({ ...f, replace: e.target.value }))}
                        placeholder="Replace with..."
                        className="bg-slate-900 border border-white/10 rounded-lg px-3 py-1.5 text-sm text-white w-40 focus:outline-none" />
                    <button onClick={doFind} className="px-2.5 py-1.5 bg-slate-700 hover:bg-slate-600 rounded-lg text-xs transition-colors">Find</button>
                    <button onClick={doReplace} className="px-2.5 py-1.5 bg-blue-600 hover:bg-blue-500 rounded-lg text-xs transition-colors">Replace All</button>
                    <label className="flex items-center gap-1 text-xs text-slate-400 cursor-pointer">
                        <input type="checkbox" checked={find.matchCase} onChange={e => setFind(f => ({ ...f, matchCase: e.target.checked }))} className="accent-blue-500" />
                        Aa
                    </label>
                    {find.count > 0 && <span className="text-xs text-slate-500">{find.count} matches</span>}
                    <button onClick={() => setFind(f => ({ ...f, show: false }))} className="ml-auto text-slate-500 hover:text-white"><X size={14} /></button>
                </div>
            )}

            {/* Editor */}
            <div className="flex-1 overflow-hidden">
                {activeTab && (
                    <textarea
                        ref={textareaRef}
                        value={activeTab.content}
                        onChange={e => updateContent(activeTab.id, e.target.value)}
                        onKeyDown={handleKeyDown}
                        onKeyUp={handleCursorMove}
                        onClick={handleCursorMove}
                        spellCheck={false}
                        className="w-full h-full bg-slate-950 text-slate-100 font-mono text-sm p-4 resize-none focus:outline-none leading-relaxed"
                        placeholder="Start typing..."
                        style={{ fontFamily: "'JetBrains Mono', 'Fira Code', monospace", tabSize: 4 }}
                    />
                )}
            </div>

            {/* Status bar */}
            <div className="shrink-0 flex items-center justify-between px-4 py-1 bg-slate-800 border-t border-white/5 text-xs text-slate-500">
                <div className="flex gap-4">
                    <span>Ln {cursorPos.line}, Col {cursorPos.col}</span>
                    <span>{lineCount} lines</span>
                    <span>{wordCount} words</span>
                    {activeTab?.content.length ? <span>{activeTab.content.length} chars</span> : null}
                </div>
                <div className="flex gap-3">
                    {activeTab?.modified && <span className="text-yellow-500">Modified</span>}
                    <span>UTF-8</span>
                    <span>Plain Text</span>
                </div>
            </div>
        </div>
    );
};
export default NotepadApp;
